#ifndef MENU_H
#define MENU_H
//function prototypes
void printMainMenu(void);
void printFileMenu(void);
void printBooksMenu(void);
void printClientsMenu(void);
void standardOperations(void);
void printOrdersMenu(void);
void printOperationsMenu(void);
size_t getOption(void);
void mainMenu(void);
void fileMenu(void);
void bookMenu(void);
void clientMenu(void);
void orderMenu(void);
void operationMenu(void);
#endif //menu_h